### PR TITLE
add strict validation hook

### PR DESCRIPTION
**Pull request by Finkregh**

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
is there a way to pass it as parameter to the existing hook instead?

**Comment by Finkregh** [comment]
> is there a way to pass it as parameter to the existing hook instead?

You can also do this:

```yaml
    hooks:
      - id: renovate-config-validator
        args: [--strict]
```

But I like having individual hooks for different behaviour, just a list with `- id: xxx`s instead of additional values.

**Comment by viceice** [comment]
Closing in favor of
- #2279

**Comment by Finkregh** [comment]
> Closing in favor of
> 
> - #2279

You linked itself? 🧐

**Comment by viceice** [comment]
> > Closing in favor of
> > 
> > - #2279
> 
> You linked itself? 🧐

ups, wrong link, fixed
- https://github.com/renovatebot/pre-commit-hooks/pull/2475

**Pull request closed without merging**
